# Generated by Django 5.1.2 on 2024-11-01 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_assetgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.assetgroup'),
        ),
    ]
