# Generated by Django 5.1.2 on 2024-11-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_floor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floor',
            old_name='building_id',
            new_name='building',
        ),
    ]
