# Generated by Django 5.1.2 on 2024-11-12 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='building_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.building'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='floor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.floor'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='unit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.units'),
        ),
    ]
