# Generated by Django 5.1.2 on 2024-11-20 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.categories'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sub_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.subcategory'),
        ),
    ]
