# Generated by Django 5.1.2 on 2024-11-25 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_ticketstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user',
            new_name='created_by',
        ),
    ]
